name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s tests

    - name: Build Docker image
      run: |
        docker build -t crypto-tracker .

    - name: Push Docker image
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker tag crypto-tracker "${{ secrets.DOCKER_USERNAME }}/crypto-tracker:${GITHUB_SHA}"
        docker push "${{ secrets.DOCKER_USERNAME }}/crypto-tracker:${GITHUB_SHA}"

    - name: Release Docker image
      if: github.event_name == 'release'
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker tag crypto-tracker "${{ secrets.DOCKER_USERNAME }}/crypto-tracker:${GITHUB_REF##*/}"
        docker push "${{ secrets.DOCKER_USERNAME }}/crypto-tracker:${GITHUB_REF##*/}"
