name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13.1'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      id: run_tests
      run: |
        python -m unittest discover -s tests

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Docker image on push
      if: steps.run_tests.outcome == 'success' && github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: "${{ secrets.DOCKER_USERNAME }}/crypto-tracker:${GITHUB_SHA::7}"

    - name: Verify release name
      if: github.event_name == 'release' && !startsWith(github.ref, 'refs/tags/v')
      run: |
        echo "Release name must start with 'v' followed by a version number"
        exit 1

    - name: Build & Push Docker image on release
      if: steps.run_tests.outcome == 'success' && github.event_name == 'release'
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/crypto-tracker:${{ github.ref_name }}